# toml configure file
# toml中key的首字母可以小写，但是对应的golang中的struct成员首字母必须大写

AppName                 = "RPC-CLIENT"

# host
LocalHost               = "127.0.0.1"

# server
# ServerHost              = "192.168.8.3"
ServerHost              = "127.0.0.1"
ServerPort              = 10000
ProfilePort             = 10080

# connection pool
# 连接池连接数目
ConnectionNum           = 10

# session
# client与server之间连接的心跳周期
HeartbeatPeriod         = "10s"
# client与server之间连接的超时时间
SessionTimeout          = "20s"

# app fail fast
FailFastTimeout         = "3s"

# tcp
[GettySessionParam]
    CompressEncoding    = true
    TcpNoDelay          = true
    TcpKeepAlive        = true
    KeepAlivePeriod     = "120s"
    TcpRBufSize         = 262144
    TcpWBufSize         = 65536
    PkgRQSize           = 512
    PkgWQSize           = 256
    TcpReadTimeout      = "1s"
    TcpWriteTimeout     = "5s"
    WaitTimeout         = "1s"
    MaxMsgLen           = 128
    SessionName         = "getty-rpc-client"

# registry
[Registry]
    Type                = "etcd"
    # Addr                = "127.0.0.1:2379"
    KeepaliveTimeout    = 5
    Root                = "/getty"
    IDC                 = "bj-unicom"
    NodeID              = "n147"
